spring:
  data:
    mongodb:
      host:
      port:
      authentication-database:
      username:
      password:
      database:
  mustache:
    charset: UTF-8
    servlet:
      expose-request-attributes: true
      expose-session-attributes: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true